# Site settings
title: Awesome Forms Documentation
email: support@awesome.ug
description: > # This Site will help you on using Awesome Forms for WordPress.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://docs.awesome-forms.com" # the base hostname & protocol for your site
twitter_username: awsmug
github_username:  awsmug

# Build settings
markdown: kramdown
